# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDd():
  def setup_method(self, method):
    self.opts = Options()
    self.opts.headless = True
    self.driver = webdriver.Chrome(options=self.opts)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dd(self):
    self.driver.get("https://allo.ua/ua/igrovye-pristavki/konsol-playstation-5-digital-edition.html")
    self.driver.set_window_size(1920, 970)
    self.driver.find_element_by_css_selector('#product-buy-button').click()
    time.sleep(5)
    
  
